model: ECAPA_TDNN
encoder_type: ECA
log_input: True
trainfunc: softmaxproto
batch_size : 276
nPerSpeaker: 3 # Do not change for triplet data configuration

C: 1024
n_mels: 80

nOut: 256
spk_dims  : 256
env_dims  : 256
disc_dims : 256
disc_out_dims : 128

lr_decay : 0.75
lr_decay_interval : 8